# Generated by Django 4.2.13 on 2024-06-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0002_userauth'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userauth',
            name='user_auth_deleted_at_idx',
        ),
        migrations.AlterModelTable(
            name='userauth',
            table=None,
        ),
    ]
