# Generated by Django 4.2.13 on 2024-06-13 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otchet', '0004_useraut_delete_userauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraut',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='useraut',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='useraut',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='report',
            name='UserAut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
