# Generated by Django 4.2.13 on 2024-06-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0005_remove_report_user_remove_useraut_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='UserAut',
        ),
        migrations.RemoveField(
            model_name='report',
            name='photos',
        ),
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otchet.photo'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_aut_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otchet.useraut'),
        ),
    ]
