# Generated by Django 4.2.13 on 2024-06-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0006_remove_report_useraut_remove_report_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_aut_id',
            new_name='user_aut',
        ),
    ]
