# Generated by Django 4.2.13 on 2024-06-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0007_rename_user_aut_id_report_user_aut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_aut',
        ),
        migrations.AddField(
            model_name='report',
            name='refresh_token',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
