# Generated by Django 4.2.13 on 2024-06-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0010_rename_object_report_objekt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='objekt',
            new_name='object_name',
        ),
    ]
